image: Visual Studio 2013
configuration: Debug

# install:
#   - set QTDIR=C:\Qt\5.5\mingw492_32
#   - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin


# before_build:
#   - set PATH=C:\msys2\bin;%QT5%\bin;%PATH%

install:
  ps:
    C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-toolchain"
    C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-qt-creator"
    # echo completed

  # - set PATH=C:\msys2\bin
  


environment:
  -compiler: msys2
  # - QT: 
  #   MINGW: 

# build:
#   project: add.cpp

# build_script:
#   - qmake test\test.pro
#   - test\make

# deploy:
# - provider: GitHub
#   auth_token:
#     secure: hQDQ9bqFo+fkhKBZtywbP7ZpnLzCxpIiMIgbWLYvcMSmdJ1BvIWFQU0HtNK9rikt
#   artifact: test