image: Visual Studio 2015
configuration: Debug

install:
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin


environment:
  -compiler: mingw

# build:
#   project: add.cpp

build_script:
  - qmake test\test.pro
  - test\make

deploy:
- provider: GitHub
  auth_token:
    secure: hQDQ9bqFo+fkhKBZtywbP7ZpnLzCxpIiMIgbWLYvcMSmdJ1BvIWFQU0HtNK9rikt
  artifact: test